config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :spaces
  resources :relationships

  root to: "spaces#index"
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :space
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number_of_days, presence: true

end

app/models/space.rb
class Space < ActiveRecord::Base

  belongs_to :user
  validates :address, presence: true
  validates :day_fee, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :full_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :full_name
  end
end

app/controllers/relationship_controller.rb
class RelationshipController < ApplicationController

  def index
    @relationship = Relationship.all
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def index
    @relationship = Relationship.all
  end

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController

  def index
    @spaces = Space.all
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    if @space.save
      flash[:notice] = "Space created"
      redirect_to root_url
    else
      flash[:alert] = "Space failed to create"
      render "new"
    end
  end

  def edit
    @space = Space.find(params[:id])
    render 'show'
  end

  def update
    @space = Space.find(params[:id])

    if @space.update(space_params)
      flash[:notice] = "Space updated"
      redirect_to root_url
    else
      flash[:alert] = "Space failed to update"
      render 'show'
    end
  end

  def destroy
    @space = Space.destroy(params[:id])
  end

private

  def space_params
    params.require(:space).permit(:user_id, :address, :day_fee, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationController

  # def devise_parameter_sanitizer
  #   UserParameterSanitizer.new(User, :user, params)
  # end

  # def user_params
  #   params.require(:user).permit(:full_name)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <div id="user_nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path %> |
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
</body>
</html>

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <div><%=f.label :address %>
  <%= f.text_field :address, autofocus: true %></div>
  <div><%=f.label :day_fee %>
  <%= f.number_field :day_fee %></div>
  <div><%=f.label :description %>
  <%= f.text_field :description %></div>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div><%= f.submit "Confirm" %></div>
<% end %>

app/views/spaces/index.html.erb
<h1> Available Spaces for BnBing </h1>

  <% @spaces.each do |space| %>
    <p><%= link_to "#{space.description}", edit_space_path(space) %></p>
  <% end %>

app/views/spaces/new.html.erb
<h1> create space </h1>

<%= render 'form' %>

app/views/spaces/show.html.erb
<%= render 'form' %>